const allowedPath = [
  /^profiles$/,
  /^profiles\/[0-9a-f-]{36}\/access-context$/,
  /^profiles\/[0-9a-f-]{36}\/access-grants$/,
  /^profiles\/[0-9a-f-]{36}\/access-grants\/[0-9a-f-]{36}$/,
  /^profiles\/[0-9a-f-]{36}\/prescriptions$/,
  /^profiles\/[0-9a-f-]{36}\/prescriptions\/[0-9a-f-]{36}\/evidence$/,
  /^profiles\/[0-9a-f-]{36}\/prescriptions\/[0-9a-f-]{36}\/evidence\/uploads$/,
  /^profiles\/[0-9a-f-]{36}\/prescriptions\/[0-9a-f-]{36}\/evidence\/[0-9a-f-]{36}\/complete$/,
  /^profiles\/[0-9a-f-]{36}\/regimens$/,
  /^profiles\/[0-9a-f-]{36}\/medications$/,
  /^profiles\/[0-9a-f-]{36}\/notifications$/,
  /^profiles\/[0-9a-f-]{36}\/notifications\/stream$/,
  /^profiles\/[0-9a-f-]{36}\/notifications\/delivery-status$/,
  /^profiles\/[0-9a-f-]{36}\/notifications\/delivery-attempts$/,
  /^profiles\/[0-9a-f-]{36}\/notification-policies$/,
  /^profiles\/[0-9a-f-]{36}\/notification-policies\/[0-9a-f-]{36}$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/reminder-schedules$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/reminder-occurrences$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/reminder-occurrences\/[0-9a-f-]{36}\/(?:snooze|acknowledge)$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/dose-logs$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/adherence\/(?:daily|weekly|monthly|streak)$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/inventory$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/inventory\/movements$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/inventory\/refills$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/inventory\/refill-alerts$/,
  /^profiles\/[0-9a-f-]{36}\/regimens\/[0-9a-f-]{36}\/inventory\/refill-alerts\/[0-9a-f-]{36}\/acknowledge$/,
  /^profiles\/[0-9a-f-]{36}\/evidence\/[0-9a-f-]{36}\/ocr-extractions$/,
  /^profiles\/[0-9a-f-]{36}\/evidence\/[0-9a-f-]{36}\/medication-drafts$/,
  /^profiles\/[0-9a-f-]{36}\/medication-drafts\/[0-9a-f-]{36}$/,
  /^profiles\/[0-9a-f-]{36}\/medication-drafts\/[0-9a-f-]{36}\/submitted$/,
  /^profiles\/[0-9a-f-]{36}\/evidence\/[0-9a-f-]{36}\/ocr-jobs\/[0-9a-f-]{36}\/lab-correlation$/,
  /^profiles\/[0-9a-f-]{36}\/evidence\/[0-9a-f-]{36}\/ocr-jobs\/[0-9a-f-]{36}\/lab-receipt-audit$/,
];

export function isAllowedCoreEvidencePath(path: string): boolean {
  return allowedPath.some((pattern) => pattern.test(path));
}
